version: 2.1

jobs:
  test-and-upload:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/mccurdyc/splitfile
    environment:
      - GO111MODULE=on
      - CC_TEST_REPORTER_ID: YOUR_REPO_CC_TEST_REPORTER_ID
    steps:
      - checkout
      - run:
          name: Install Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Collect Test Coverage
          command: |
            go mod download
            go test -coverprofile c.out ./...
            # have to format coverage to work with Go >1.11 and Modules - https://github.com/codeclimate/test-reporter/issues/363
            ./cc-test-reporter after-build --prefix github.com/mccurdyc/splitfile --coverage-input-type gocov --exit-code $?
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  test:
    jobs:
      - test-and-upload
